# Generated by Django 4.0.3 on 2022-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcodes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
